# Build the docker image and publish it to gitlabs repository

image: 
  name: registry.hub.docker.com/nextflow/nextflow:21.12.1-edge

services: 
  - name: registry.hub.docker.com/library/docker:20.10.14-dind
    command: ["--tls=false"]
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build1:
  stage: build
  script:
    - nextflow run . --push