dockerimage-build:
  ## using buildah like described at https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-alternatives
  image: quay.io/buildah/stable
  stage: build
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: vfs
    # You may need this workaround for some errors: https://stackoverflow.com/a/70438141/1233435
    #BUILDAH_ISOLATION: chroot
    # define image names
    IMAGE_NAME_FQ: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_NAME_LATEST: $CI_REGISTRY_IMAGE:latest    
  script:
    # configure short-name-mode as described at https://www.redhat.com/sysadmin/container-image-short-names
    # this removes 'Error: creating build container: short-name resolution enforced but cannot prompt without a TTY'
    - sed -i '/short-name-mode=.*/c\short-name-mode="disabled"' /etc/containers/registries.conf
    - tail /etc/containers/registries.conf
    # Log in to the GitLab container registry
    - buildah info
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "login to docker registry successfull"
    - buildah images
    - buildah build -t $IMAGE_NAME_FQ
    - buildah images
    - buildah push $IMAGE_NAME_FQ
    - if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then buildah tag $IMAGE_NAME_FQ $IMAGE_NAME_LATEST; buildah push $IMAGE_NAME_LATEST; fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - exists:
        - Dockerfile